### ISSUE TITLE
Demo and screencast

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/orion-glpi-plugin#10]
Hi, @btry 

Could you deploy this plugin in the deploy this plugin here:
http://dev.flyve.org/glpi/

And record a screencast and upload as not listed on Youtube and share the link here in the issue.

Thanks.

**Comment by ajsb85** [comment]
Hi, @btry 

We need the screencast for the 15th of November.

Thanks.

**Comment by btry** [comment]
screencast done
