### ISSUE TITLE
Project management

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/orion-glpi-plugin#2]
Hi, @btry 

No commits from 5 days ago in this repository.
Could you create the task based on the documentation?
And add these tasks in order of priority in the backlog list.
Create your PRs in WIP to see the progress.

btw, this commit subject is too long

![imagen](https://user-images.githubusercontent.com/663460/31206159-647c944a-a976-11e7-9838-45a7c5c9494b.png)

Thank you.

**Comment by ajsb85** [comment]
Hi, @Naylin15 / @btry 

Keep the project board up to date. 👍

**Comment by btry** [comment]
Having a good tool for project management is necessary. The board is way too much limited,
