### ISSUE TITLE
Continuos Deploy

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/orion-glpi-plugin#8]
Hi, @btry 

Could you integrate the API of the GLPI Plugins with Travis CI to deploy the plugin in every tag creation?

http://plugins.glpi-project.org/#/developer/guides

Thank you.

**Comment by ajsb85** [comment]
Hi again, @btry 

Could you upload (with Travis CI) the artifacts to the GitHub release section.

Thanks.

**Comment by btry** [comment]
There is nothing to do. Once the plugin is declared and approved, updating the XML file in the master branch (by merging a git flow release) is sufficient.

**Comment by ajsb85** [comment]
@btry Very good, so this task is only for the artifacts in the GitHub section.

**Comment by btry** [comment]
duplicates #11
